require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MallsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Mall. As you add validations to Mall, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MallsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all malls as @malls" do
      mall = Mall.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:malls)).to eq([mall])
    end
  end

  describe "GET #show" do
    it "assigns the requested mall as @mall" do
      mall = Mall.create! valid_attributes
      get :show, params: {id: mall.to_param}, session: valid_session
      expect(assigns(:mall)).to eq(mall)
    end
  end

  describe "GET #new" do
    it "assigns a new mall as @mall" do
      get :new, params: {}, session: valid_session
      expect(assigns(:mall)).to be_a_new(Mall)
    end
  end

  describe "GET #edit" do
    it "assigns the requested mall as @mall" do
      mall = Mall.create! valid_attributes
      get :edit, params: {id: mall.to_param}, session: valid_session
      expect(assigns(:mall)).to eq(mall)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Mall" do
        expect {
          post :create, params: {mall: valid_attributes}, session: valid_session
        }.to change(Mall, :count).by(1)
      end

      it "assigns a newly created mall as @mall" do
        post :create, params: {mall: valid_attributes}, session: valid_session
        expect(assigns(:mall)).to be_a(Mall)
        expect(assigns(:mall)).to be_persisted
      end

      it "redirects to the created mall" do
        post :create, params: {mall: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Mall.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved mall as @mall" do
        post :create, params: {mall: invalid_attributes}, session: valid_session
        expect(assigns(:mall)).to be_a_new(Mall)
      end

      it "re-renders the 'new' template" do
        post :create, params: {mall: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested mall" do
        mall = Mall.create! valid_attributes
        put :update, params: {id: mall.to_param, mall: new_attributes}, session: valid_session
        mall.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested mall as @mall" do
        mall = Mall.create! valid_attributes
        put :update, params: {id: mall.to_param, mall: valid_attributes}, session: valid_session
        expect(assigns(:mall)).to eq(mall)
      end

      it "redirects to the mall" do
        mall = Mall.create! valid_attributes
        put :update, params: {id: mall.to_param, mall: valid_attributes}, session: valid_session
        expect(response).to redirect_to(mall)
      end
    end

    context "with invalid params" do
      it "assigns the mall as @mall" do
        mall = Mall.create! valid_attributes
        put :update, params: {id: mall.to_param, mall: invalid_attributes}, session: valid_session
        expect(assigns(:mall)).to eq(mall)
      end

      it "re-renders the 'edit' template" do
        mall = Mall.create! valid_attributes
        put :update, params: {id: mall.to_param, mall: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested mall" do
      mall = Mall.create! valid_attributes
      expect {
        delete :destroy, params: {id: mall.to_param}, session: valid_session
      }.to change(Mall, :count).by(-1)
    end

    it "redirects to the malls list" do
      mall = Mall.create! valid_attributes
      delete :destroy, params: {id: mall.to_param}, session: valid_session
      expect(response).to redirect_to(malls_url)
    end
  end

end
